### ISSUE TITLE
Cannot Assign Requested Address

### ISSUE THREAD

**Issue by Gzhang-umich** [microsoft/Graphormer#110]
I want to reproduce the ZINC pretrain. However, I meet the problem with the log:
Traceback (most recent call last):
  File "/opt/conda/envs/graphormer-env/lib/python3.7/urllib/request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/conda/envs/graphormer-env/lib/python3.7/http/client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/http/client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/http/client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/http/client.py", line 1036, in _send_output
    self.send(msg)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/http/client.py", line 976, in send
    self.connect()
  File "/opt/conda/envs/graphormer-env/lib/python3.7/http/client.py", line 1443, in connect
    super().connect()
  File "/opt/conda/envs/graphormer-env/lib/python3.7/http/client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/opt/conda/envs/graphormer-env/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/graphormer-env/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/opt/conda/envs/graphormer-env/lib/python3.7/site-packages/fairseq_cli/train.py", line 557, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/site-packages/fairseq/distributed/utils.py", line 369, in call_main
    main(cfg, **kwargs)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/site-packages/fairseq_cli/train.py", line 87, in main
    task = tasks.setup_task(cfg.task)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/site-packages/fairseq/tasks/__init__.py", line 46, in setup_task
    return task.setup_task(cfg, **kwargs)
  File "/~/graphormer-env-docker/Graphormer/graphormer/tasks/graph_prediction.py", line 179, in setup_task
    return cls(cfg)
  File "/~/graphormer-env-docker/Graphormer/graphormer/tasks/graph_prediction.py", line 158, in __init__
    seed=cfg.seed,
  File "/~/graphormer-env-docker/Graphormer/graphormer/data/dataset.py", line 84, in __init__
    self.dataset = PYGDatasetLookupTable.GetPYGDataset(dataset_spec, seed=seed)
  File "/~/graphormer-env-docker/Graphormer/graphormer/data/pyg_datasets/pyg_dataset_lookup_table.py", line 90, in GetPYGDataset
    inner_dataset = MyZINC(root=root)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/site-packages/torch_geometric/datasets/zinc.py", line 54, in __init__
    super(ZINC, self).__init__(root, transform, pre_transform, pre_filter)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/site-packages/torch_geometric/data/in_memory_dataset.py", line 60, in __init__
    super().__init__(root, transform, pre_transform, pre_filter)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 83, in __init__
    self._download()
  File "/opt/conda/envs/graphormer-env/lib/python3.7/site-packages/torch_geometric/data/dataset.py", line 140, in _download
    self.download()
  File "/~/graphormer-env-docker/Graphormer/graphormer/data/pyg_datasets/pyg_dataset_lookup_table.py", line 41, in download
    super(MyZINC, self).download()
  File "/opt/conda/envs/graphormer-env/lib/python3.7/site-packages/torch_geometric/datasets/zinc.py", line 76, in download
    path = download_url(self.url, self.root)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/site-packages/torch_geometric/data/download.py", line 34, in download_url
    data = urllib.request.urlopen(url, context=context)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/opt/conda/envs/graphormer-env/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

I understand that it might due to my network problem. But how can I run the code without network.

**Comment by Ericmututu** [comment]
Hi, you can try to move `molecules.zip` (download in advance) to `.../examples/property_prediction/dataset/`, then execute the `zinc.sh` script. It is work for me.
