### ISSUE TITLE
Issue running `bash zinc.sh` after fresh install (Ubuntu)

### ISSUE THREAD

**Issue by JacobHelwig** [microsoft/Graphormer#130]
I run the code exactly from the installation guide:
```
conda create -n graphormer python=3.9
conda activate graphormer
git clone --recursive https://github.com/microsoft/Graphormer.git
cd Graphormer
```
I then run the following: 
```
bash install.sh
bash examples/property_prediction/zinc.sh
```
And get an error:
```
zinc.sh: line 5: fairseq-train: command not found
```
So I install fairseq:
```
cd fairseq/
pip install --editable ./
```
I then again try running `zinc.sh` and get:
```
Traceback (most recent call last):
  File "/mnt/data/shared/jacob/Graphormer/fairseq/fairseq/logging/progress_bar.py", line 315, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/data/jacob/anaconda3/envs/graphormer/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 1, in <module>
    import tensorboard
ModuleNotFoundError: No module named 'tensorboard'
```
So I install `tensorboard` and retry:
```
conda install tensorboard
bash zinc.sh
```
And get the error:
```
Traceback (most recent call last):
  File "/data/jacob/anaconda3/envs/graphormer/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq', 'console_scripts', 'fairseq-train')())
  File "/data/jacob/anaconda3/envs/graphormer/bin/fairseq-train", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/data/jacob/anaconda3/envs/graphormer/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/data/jacob/anaconda3/envs/graphormer/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/mnt/data/shared/jacob/Graphormer/fairseq/fairseq_cli/train.py", line 30, in <module>
    from fairseq import checkpoint_utils, options, quantization_utils, tasks, utils
  File "/mnt/data/shared/jacob/Graphormer/fairseq/fairseq/__init__.py", line 21, in <module>
    from fairseq.logging import meters, metrics, progress_bar  # noqa
  File "/mnt/data/shared/jacob/Graphormer/fairseq/fairseq/logging/progress_bar.py", line 315, in <module>
    from torch.utils.tensorboard import SummaryWriter
  File "/data/jacob/anaconda3/envs/graphormer/lib/python3.9/site-packages/torch/utils/tensorboard/__init__.py", line 4, in <module>
    LooseVersion = distutils.version.LooseVersion
AttributeError: module 'distutils' has no attribute 'version'
```
 Here are the details about my conda environment:
```
conda list
# packages in environment at /data/jacob/anaconda3/envs/graphormer:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   0.15.0             pyhd3eb1b0_0  
aiohttp                   3.8.1            py39h7f8727e_1  
aiosignal                 1.2.0              pyhd3eb1b0_0  
antlr4-python3-runtime    4.8                      pypi_0    pypi
async-timeout             4.0.1              pyhd3eb1b0_0  
attrs                     21.4.0             pyhd3eb1b0_0  
bitarray                  2.6.0                    pypi_0    pypi
blas                      1.0                         mkl  
blinker                   1.4              py39h06a4308_0  
brotlipy                  0.7.0           py39h27cfd23_1003  
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2022.07.19           h06a4308_0  
cachetools                4.2.2              pyhd3eb1b0_0  
certifi                   2022.6.15        py39h06a4308_0  
cffi                      1.15.1           py39h74dc2b5_0  
charset-normalizer        2.1.0                    pypi_0    pypi
click                     8.0.4            py39h06a4308_0  
colorama                  0.4.5                    pypi_0    pypi
cryptography              37.0.1           py39h9ce1e76_0  
cython                    0.29.32                  pypi_0    pypi
dataclasses               0.8                pyh6d0b6a4_7  
dgl                       0.7.2                    pypi_0    pypi
fairseq                   1.0.0a0+98ebe4f           dev_0    <develop>
frozenlist                1.2.0            py39h7f8727e_0  
google-auth               2.6.0              pyhd3eb1b0_0  
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0  
googledrivedownloader     0.4                      pypi_0    pypi
grpcio                    1.42.0           py39hce63b2e_0  
hydra-core                1.0.7                    pypi_0    pypi
idna                      3.3                pyhd3eb1b0_0  
importlib-metadata        4.11.3           py39h06a4308_0  
intel-openmp              2021.4.0          h06a4308_3561  
isodate                   0.6.1                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libprotobuf               3.20.1               h4ff587b_0  
libstdcxx-ng              11.2.0               h1234567_1  
littleutils               0.2.2                    pypi_0    pypi
lmdb                      1.3.0                    pypi_0    pypi
lxml                      4.9.1                    pypi_0    pypi
markdown                  3.3.4            py39h06a4308_0  
markupsafe                2.1.1                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
multidict                 5.2.0            py39h7f8727e_2  
ncurses                   6.3                  h5eee18b_3  
networkx                  2.8.5                    pypi_0    pypi
numpy                     1.23.1           py39h6c91a56_0  
numpy-base                1.23.1           py39ha15fc14_0  
oauthlib                  3.2.0              pyhd3eb1b0_1  
ogb                       1.3.2                    pypi_0    pypi
omegaconf                 2.0.6                    pypi_0    pypi
openssl                   1.1.1q               h7f8727e_0  
outdated                  0.2.1                    pypi_0    pypi
pandas                    1.4.3                    pypi_0    pypi
pip                       22.1.2           py39h06a4308_0  
portalocker               2.5.1                    pypi_0    pypi
protobuf                  4.21.4                   pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyjwt                     2.4.0            py39h06a4308_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.12               h12debd9_1  
python-dateutil           2.8.2                    pypi_0    pypi
python-louvain            0.16                     pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
rdflib                    6.2.0                    pypi_0    pypi
rdkit-pypi                2021.9.3                 pypi_0    pypi
readline                  8.1.2                h7f8727e_1  
regex                     2022.7.25                pypi_0    pypi
requests                  2.28.1           py39h06a4308_0  
requests-oauthlib         1.3.0                      py_0  
rsa                       4.7.2              pyhd3eb1b0_1  
sacrebleu                 2.2.0                    pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.9.0                    pypi_0    pypi
setuptools                61.2.0           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.39.2               h5082296_0  
tabulate                  0.8.10                   pypi_0    pypi
tensorboard               2.8.0            py39h06a4308_0  
tensorboard-data-server   0.6.0            py39hca6d32c_0  
tensorboard-plugin-wit    1.8.1            py39h06a4308_0  
tensorboardx              2.4.1                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torch                     1.9.1+cu111              pypi_0    pypi
torch-geometric           1.7.2                    pypi_0    pypi
torch-scatter             2.0.9                    pypi_0    pypi
torch-sparse              0.6.12                   pypi_0    pypi
torchaudio                0.9.1                    pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
typing-extensions         4.3.0            py39h06a4308_0  
typing_extensions         4.3.0            py39h06a4308_0  
tzdata                    2022a                hda174b7_0  
urllib3                   1.26.11          py39h06a4308_0  
werkzeug                  2.0.3              pyhd3eb1b0_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h7f8727e_1  
yarl                      1.6.3            py39h27cfd23_0  
zipp                      3.8.0            py39h06a4308_0  
zlib                      1.2.12               h7f8727e_2  
```
And OS details:
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
```

**Comment by JacobHelwig** [comment]
Solution was running `pip uninstall tensorboard`. Then, I am able to run `zinc.sh`. Here is my conda environment:

```
# packages in environment at /data/jacob/anaconda3/envs/graphormer:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
absl-py                   0.15.0             pyhd3eb1b0_0  
aiohttp                   3.8.1            py39h7f8727e_1  
aiosignal                 1.2.0              pyhd3eb1b0_0  
antlr4-python3-runtime    4.8                      pypi_0    pypi
async-timeout             4.0.1              pyhd3eb1b0_0  
attrs                     21.4.0             pyhd3eb1b0_0  
bitarray                  2.6.0                    pypi_0    pypi
blas                      1.0                         mkl  
blinker                   1.4              py39h06a4308_0  
brotlipy                  0.7.0           py39h27cfd23_1003  
c-ares                    1.18.1               h7f8727e_0  
ca-certificates           2022.07.19           h06a4308_0  
cachetools                4.2.2              pyhd3eb1b0_0  
certifi                   2022.6.15        py39h06a4308_0  
cffi                      1.15.1           py39h74dc2b5_0  
charset-normalizer        2.1.0                    pypi_0    pypi
click                     8.0.4            py39h06a4308_0  
colorama                  0.4.5                    pypi_0    pypi
cryptography              37.0.1           py39h9ce1e76_0  
cython                    0.29.32                  pypi_0    pypi
dataclasses               0.8                pyh6d0b6a4_7  
dgl                       0.7.2                    pypi_0    pypi
fairseq                   1.0.0a0+98ebe4f           dev_0    <develop>
frozenlist                1.2.0            py39h7f8727e_0  
google-auth               2.6.0              pyhd3eb1b0_0  
google-auth-oauthlib      0.4.4              pyhd3eb1b0_0  
googledrivedownloader     0.4                      pypi_0    pypi
grpcio                    1.42.0           py39hce63b2e_0  
hydra-core                1.0.7                    pypi_0    pypi
idna                      3.3                pyhd3eb1b0_0  
importlib-metadata        4.11.3           py39h06a4308_0  
intel-openmp              2021.4.0          h06a4308_3561  
isodate                   0.6.1                    pypi_0    pypi
jinja2                    3.1.2                    pypi_0    pypi
joblib                    1.1.0                    pypi_0    pypi
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.3                  he6710b0_2  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libprotobuf               3.20.1               h4ff587b_0  
libstdcxx-ng              11.2.0               h1234567_1  
littleutils               0.2.2                    pypi_0    pypi
lmdb                      1.3.0                    pypi_0    pypi
lxml                      4.9.1                    pypi_0    pypi
markdown                  3.3.4            py39h06a4308_0  
markupsafe                2.1.1                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py39h7f8727e_0  
mkl_fft                   1.3.1            py39hd3c417c_0  
mkl_random                1.2.2            py39h51133e4_0  
multidict                 5.2.0            py39h7f8727e_2  
ncurses                   6.3                  h5eee18b_3  
networkx                  2.8.5                    pypi_0    pypi
numpy                     1.23.1           py39h6c91a56_0  
numpy-base                1.23.1           py39ha15fc14_0  
oauthlib                  3.2.0              pyhd3eb1b0_1  
ogb                       1.3.2                    pypi_0    pypi
omegaconf                 2.0.6                    pypi_0    pypi
openssl                   1.1.1q               h7f8727e_0  
outdated                  0.2.1                    pypi_0    pypi
pandas                    1.4.3                    pypi_0    pypi
pip                       22.1.2           py39h06a4308_0  
portalocker               2.5.1                    pypi_0    pypi
protobuf                  4.21.4                   pypi_0    pypi
pyasn1                    0.4.8              pyhd3eb1b0_0  
pyasn1-modules            0.2.8                      py_0  
pycparser                 2.21               pyhd3eb1b0_0  
pyjwt                     2.4.0            py39h06a4308_0  
pyopenssl                 22.0.0             pyhd3eb1b0_0  
pyparsing                 3.0.9                    pypi_0    pypi
pysocks                   1.7.1            py39h06a4308_0  
python                    3.9.12               h12debd9_1  
python-dateutil           2.8.2                    pypi_0    pypi
python-louvain            0.16                     pypi_0    pypi
pytz                      2022.1                   pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
rdflib                    6.2.0                    pypi_0    pypi
rdkit-pypi                2021.9.3                 pypi_0    pypi
readline                  8.1.2                h7f8727e_1  
regex                     2022.7.25                pypi_0    pypi
requests                  2.28.1           py39h06a4308_0  
requests-oauthlib         1.3.0                      py_0  
rsa                       4.7.2              pyhd3eb1b0_1  
sacrebleu                 2.2.0                    pypi_0    pypi
scikit-learn              1.1.2                    pypi_0    pypi
scipy                     1.9.0                    pypi_0    pypi
setuptools                61.2.0           py39h06a4308_0  
six                       1.16.0             pyhd3eb1b0_1  
sqlite                    3.39.2               h5082296_0  
tabulate                  0.8.10                   pypi_0    pypi
tensorboard-data-server   0.6.0            py39hca6d32c_0  
tensorboard-plugin-wit    1.8.1            py39h06a4308_0  
tensorboardx              2.4.1                    pypi_0    pypi
threadpoolctl             3.1.0                    pypi_0    pypi
tk                        8.6.12               h1ccaba5_0  
torch                     1.9.1+cu111              pypi_0    pypi
torch-geometric           1.7.2                    pypi_0    pypi
torch-scatter             2.0.9                    pypi_0    pypi
torch-sparse              0.6.12                   pypi_0    pypi
torchaudio                0.9.1                    pypi_0    pypi
tqdm                      4.64.0                   pypi_0    pypi
typing-extensions         4.3.0            py39h06a4308_0  
typing_extensions         4.3.0            py39h06a4308_0  
tzdata                    2022a                hda174b7_0  
urllib3                   1.26.11          py39h06a4308_0  
werkzeug                  2.0.3              pyhd3eb1b0_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.5                h7f8727e_1  
yarl                      1.6.3            py39h27cfd23_0  
zipp                      3.8.0            py39h06a4308_0  
zlib                      1.2.12               h7f8727e_2  
```

**Comment by zhenpingli** [comment]
interesting! I tried his work. It works. 
First install tensorboard,
then drop it.....
