### ISSUE TITLE
Unable to download pretrain model.HTTP error 409

### ISSUE THREAD

**Issue by yinliangying** [microsoft/Graphormer#170]
thanks for your delicate project.when I ran the evluate.py , it brake off at  model-downloading stage. The error message was `Traceback (most recent call last):
  File "/data/Graphormer/graphormer/evaluate/evaluate.py", line 130, in <module>
    main()
  File "/data/Graphormer/graphormer/evaluate/evaluate.py", line 120, in main
    eval(args, True, logger=logger)
  File "/data/Graphormer/graphormer/evaluate/evaluate.py", line 27, in eval
    model = task.build_model(cfg.model)
  File "/data/Graphormer/graphormer/tasks/graph_prediction.py", line 229, in build_model
    model = models.build_model(cfg, self)
  File "/data/fairseq/fairseq/models/__init__.py", line 105, in build_model
    return model.build_model(cfg, task)
  File "/data/Graphormer/graphormer/models/graphormer.py", line 149, in build_model
    return cls(args, encoder)
  File "/data/Graphormer/graphormer/models/graphormer.py", line 43, in __init__
    self.load_state_dict(load_pretrained_model(args.pretrained_model_name))
  File "/data/Graphormer/graphormer/pretrain/__init__.py", line 15, in load_pretrained_model
    return load_state_dict_from_url(PRETRAINED_MODEL_URLS[pretrained_model_name], progress=True)["model"]
  File "/opt/mamba/envs/graphormer/lib/python3.9/site-packages/torch/hub.py", line 571, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/opt/mamba/envs/graphormer/lib/python3.9/site-packages/torch/hub.py", line 437, in download_url_to_file
    u = urlopen(req)
  File "/opt/mamba/envs/graphormer/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/mamba/envs/graphormer/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/opt/mamba/envs/graphormer/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/opt/mamba/envs/graphormer/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/opt/mamba/envs/graphormer/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/opt/mamba/envs/graphormer/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 409: Public access is not permitted on this storage account.
(graphormer) root@bohrium-17396-1029993:/data/Graphormer/graphormer/evaluate# 
(graphormer) root@bohrium-17396-1029993:/data/Graphormer/graphormer/evaluate# vi /data/Graphormer/graphormer/pretrain/__init__.py
(graphormer) root@bohrium-17396-1029993:/data/Graphormer/graphormer/evaluate# vi /data/Graphormer/graphormer/pretrain/__init__.py
(graphormer) root@bohrium-17396-1029993:/data/Graphormer/graphormer/evaluate# wget https://ml2md.blob.core.windows.net/graphormer-ckpts/checkpoint_best_pcqm4mv1.pt
--2023-07-21 15:07:36--  https://ml2md.blob.core.windows.net/graphormer-ckpts/checkpoint_best_pcqm4mv1.pt
Resolving ml2md.blob.core.windows.net (ml2md.blob.core.windows.net)... 20.150.87.132
Connecting to ml2md.blob.core.windows.net (ml2md.blob.core.windows.net)|20.150.87.132|:443... connected.
HTTP request sent, awaiting response... 409 Public access is not permitted on this storage account.
2023-07-21 15:07:37 ERROR 409: Public access is not permitted on this storage account..`  

When I download the model url https://ml2md.blob.core.windows.net/graphormer-ckpts/checkpoint_best_pcqm4mv1.pt  manually using wget, it gave the same HTTP error.

My question is how could I fix the bug?

**Comment by AmrSheta22** [comment]
Same, have you found a solution

**Comment by ClarkChan1995** [comment]
@msftgits the issue of downloading is still ongoing. Could you solve it for once?

**Comment by smurf-1119** [comment]
I also encounter this issue, how to solve it?
