### ISSUE TITLE
json.decoder.JSONDecodeError ？？？

### ISSUE THREAD

**Issue by A-generous-miser** [microsoft/Graphormer#186]
`2024-05-09 13:01:52 | WARNING | root | The OGB package is out of date. Your version is 1.3.2, while the latest version is 1.3.6.
Traceback (most recent call last):
  File "/home/zzy/local/anaconda3/envs/graphormer2/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/site-packages/fairseq_cli/train.py", line 541, in cli_main
    parser = options.get_training_parser()
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/site-packages/fairseq/options.py", line 38, in get_training_parser
    parser = get_parser("Trainer", default_task)
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/site-packages/fairseq/options.py", line 234, in get_parser
    utils.import_user_module(usr_args)
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/site-packages/fairseq/utils.py", line 497, in import_user_module
    import_tasks(tasks_path, f"{module_name}.tasks")
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/site-packages/fairseq/tasks/__init__.py", line 117, in import_tasks
    importlib.import_module(namespace + "." + task_name)
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zzy/code/Graphormer/graphormer/tasks/is2re.py", line 23, in <module>
    from ..data.dataset import EpochShuffleDataset
  File "/home/zzy/code/Graphormer/graphormer/data/dataset.py", line 9, in <module>
    from .wrapper import MyPygGraphPropPredDataset
  File "/home/zzy/code/Graphormer/graphormer/data/wrapper.py", line 7, in <module>
    from ogb.graphproppred import PygGraphPropPredDataset
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/site-packages/ogb/graphproppred/__init__.py", line 10, in <module>
    from .dataset_dgl import DglGraphPropPredDataset
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/site-packages/ogb/graphproppred/dataset_dgl.py", line 6, in <module>
    from dgl.data.utils import load_graphs, save_graphs, Subset
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/site-packages/dgl/__init__.py", line 13, in <module>
    from .backend import load_backend, backend_name
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/site-packages/dgl/backend/__init__.py", line 107, in <module>
    load_backend(get_preferred_backend())
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/site-packages/dgl/backend/__init__.py", line 95, in get_preferred_backend
    config_dict = json.load(config_file)
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/zzy/local/anaconda3/envs/graphormer2/lib/python3.9/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 2 column 1 (char 23)`

what's the problem？

**Comment by A-generous-miser** [comment]
OK，i see
